char write_wav_header_header[44];
char *write_wav_header_p;
write_wav_header() {
  unsigned tmp___44;
  write_wav_header_p = write_wav_header_header;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  write_wav_header_p++;
  tmp___44 = write_wav_header_p;
  airac_observe(tmp___44, 0);
}
